### ISSUE TITLE
My trips list

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#1]
## Value proposition

As an User
I want a see a list of my trips
So that I can see my trips

## Description

![Image](https://user-images.githubusercontent.com/17503662/229478510-f6321510-a6a9-4948-98f2-5f5aef97a91a.png)

## Acceptance criteria

- [ ] all trips are displayed as a list 🏝
- [ ]  the list should have it's own headline
- [ ] sorted by date
- [ ] the list displays the trips and time 

## Tasks
- [ ] create a dummy data file trips.json
- [ ] create an trips array in trips.json
- [ ] create the page which renders the component TripList and Header
- [ ] create link on index.html to leads to the list page
- [ ] create a component TripList
- [ ] create component Header with props headline
- [ ]  all acceptance criteria marked with 🏝 are covered by component testing

**Comment by Satttoshi** [comment]
Small addition, consider adding a complexity rating or weigth, so after a week you have a good overview of how much you're capable of

else lgtm 🚀
