### ISSUE TITLE
List of trips

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#1]

**Comment by malgosiam** [comment]
## I can see a list of my planned places

## Value proposition

As an User
I want a see a list of my planned places
So that I can plan my trips

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] all places are displayed in a list
- [ ]  the list should have it's own headline
- [ ] sorted by date
- [ ] the list displays the places, time and likes

## Tasks

- [ ] List the tasks that need to be performed within the dev team
