### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#10]
## Value proposition

As an User
I want to see a clear title on the homepage
So that I can quickly understand the purpose of the app

## Description

![Image](https://user-images.githubusercontent.com/17503662/231210960-81f11209-50e5-4a45-9d15-128230ae42cf.png)

## Acceptance criteria
- [ ] the title is displayed on the homepage
- [ ] the font size and style of the title are easy to read and visually appealing
- [ ] the title accurately reflects the purpose of the app
- [ ] the app logo is displayed on the homepage

## Tasks
- [ ] create the homepage
- [ ] implement the title design on the homepage, using appropriate font size, style, and color
- [ ] add the logo
