### ISSUE TITLE
Add new places

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#16]
## Value proposition

As an User
I want to be able to add new places
So that I can plan my trips in the future

## Description

![Image](https://user-images.githubusercontent.com/17503662/233400114-d5753d3d-0282-43be-bd41-b54313e0520c.png)

## Acceptance criteria

- [ ] an add button on the places list page leading to a new place form
- [ ] in the new places form the user can input the place name, rating, location, and description
- [ ] the place name is required input, rating, location and description are optional
- [ ] the “add” submit button adds the new place to the places list
- [ ] after submitting the new place, the user is redirected to the places list page
- [ ] back button is available to allow the user to return to the places list page

## Tasks
- [ ] add “Add new place” button
- [ ] create new place form
- [ ] link “Add new place” button to the form
- [ ] add submit and back button

**Comment by CJAkkuec** [comment]
Hey there,
looking good so far!

I think the acceptance criteria and tasks should also reflect the need to route the user to an overview of sorts, such as the place where the newly added places and old places are displayed. It always feels a little "suspicious" to the user if they hit submit and nothing happens. If you don't want to route the user immediately, you can also have a little toast notification such as "New place added!". Or you can have both. I'd definitely implement one solution, though.

**Comment by malgosiam** [comment]
Hey @CJAkkuec ! Thanks for the review. The second-to-last point in the acceptance criteria already specifies that once the user submits the new place, they should be redirected to the page that lists all places. 
Best

**Comment by CJAkkuec** [comment]
True, I'd still mention the routing as a task :)!

**Comment by malgosiam** [comment]
I updated my tasks :)
