### ISSUE TITLE
Packing list

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#18]
## Value proposition

As an User
I want a see a list of items that I need to take
So that I can remember what I will take with me

## Description

![Image](https://user-images.githubusercontent.com/17503662/234010046-32d4d519-f764-459e-b94d-7822648e45d8.png)

## Acceptance criteria

- [ ] all items should be displayed in a list
- [ ] the list should have its own headline
- [ ] the list should display the name of each item, the quantity, and a checkbox that can be checked to indicate whether the item has been packed

## Tasks

- [ ] create a database to store the packing list items
- [ ] create packing list page which renders the component PackingList and Header
- [ ] implement logic to display all items (with name and quantity) in a list on the packing list page
- [ ] add header with headline
- [ ] add a checkbox next to each item in the packing list that can be checked by the user to indicate that the item has been packed
