### ISSUE TITLE
Add new trips

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#2]
## Value proposition

As an User
I want to be able to add new trips
So that I can plan my trips

## Description

![Image](https://user-images.githubusercontent.com/17503662/229479582-a4928fce-2532-434e-bab3-e15ce8615456.png)

## Acceptance criteria

- [ ] an add button on the my trips page leads to an new trip form
- [ ] in the new trip form trips data can be inserted
- [ ] the trip town and time are required inputs
- [ ] the submit button adds trip to the trips list.
- [ ] after the submit the user gets redirected to trip profile
- [ ] there is a back button to go back to the home page

## Tasks
- [ ] add an add-button on the my trips page
- [ ] create new trip page
- [ ] link add button with the new trip page
- [ ] create an form component for the create page
- [ ] write a function that handles the submit and add it to the trip list
- [ ]  All acceptance criteria marked with 🏝 are covered by component testing
