### ISSUE TITLE
My trip page

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#4]
## Value proposition

As an User
I want a see an page of my trip
So that I can add new informations

## Description

![Image](https://user-images.githubusercontent.com/17503662/229489950-512d93d9-290f-4b33-b205-4c9fabc5dc2e.png)

## Acceptance criteria

- [ ] the page should have it's own headline 
- [ ] headline should have a name of a town
- [ ] the page displays four buttons to add more infos
- [ ] the page displays a back button

## Tasks
- [ ] create new town page with [id]
- [ ] add all five buttons
- [ ]  all acceptance criteria marked with 🏝 are covered by component testing

**Comment by abieber1408** [comment]
LGTM! I don't understand the last Task.

**Comment by malgosiam** [comment]
hey Anita @abieber1408  , thanks! It means that if I would like to add any test, acceptance criteria to be tested should be marked with a sign 🏝. Please let me know if i understand this. Best

**Comment by abieber1408** [comment]
Hi. I got it. I can not see it in your drawing. But I think if you understand it, it is what at the last matters.

**Comment by malgosiam** [comment]
This is not something that you can see in the drawing. The sentence that you're referring to is related to testing and cannot be seen in the wireframe. You can only find it and mark it in the text, such as in the recap project 5 instructions for the art gallery app.
