### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#6]
## Value proposition

As an User
I want to delete the trip
So that trips can be removed from the list.

## Description

![Image](https://user-images.githubusercontent.com/17503662/231115160-b4effe2e-5c38-499a-a741-21a98ffe7f5f.png)

## Acceptance criteria

- [ ] delete button on the trip page that prompts a modal which asks if you really want to delete the trip
- [ ] clicking on yes in the modal deletes the trip and redirects you to the trip list
- [ ] clicking on no closes the modal and does not delete the trip

## Tasks
- [ ] add delete button
- [ ] create a modal component
- [ ] link the delete button to modal
- [ ] write delete function
- [ ] redirect to the trip list after delete
- [ ] close the modal after clicking no
