### ISSUE TITLE
Change Dates Button

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#7]
## Value proposition

As an User
I want to change dates of my trip
So that I can update the trip dates.

## Description

![Image](https://user-images.githubusercontent.com/17503662/231125416-983558f7-14ea-4fa0-b6a8-e5ddbbf29e17.png)

## Acceptance criteria

- [ ] change dates button on the trip page
- [ ] after clicking the change dates button, start Date and end Date are editable
- [ ] after clicking the submit button, i get redirected to the view of the trip

## Tasks
- [ ]  add change dates button
- [ ]  link change dates button to edit form
- [ ]  write the edit function
- [ ]  redirect to the view of the trip

**Comment by Kevinwey** [comment]
I think It sounds a little bit like you repeat yourself, maybe you write it like that "**As a** user
**I want to** have the ability to modify the dates of my trip
**so that** I can easily update my travel plans." but thats only my point of view. Rest LGTM :)

**Comment by malgosiam** [comment]
I changed it. Thank you Kevin! :)
