### ISSUE TITLE
My places list

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#8]
## Value proposition

As an User
I want a see a list of my places
So that I can plan my trip

## Description

![Image](https://user-images.githubusercontent.com/17503662/229490365-cf762cbc-7297-4932-9da3-5d2cf57530e4.png)

## Acceptance criteria

- [ ] all places are displayed as a list 
- [ ] the list should have its own headline
- [ ] the list displays the places, likes and delete buttons 
- [ ] the page displays four buttons (Add more places, Share list, Export list and back button)

## Tasks
- [ ] create places page which renders the component PlacesList and Header
- [ ] create a component PlacesList
- [ ] link the page with the trip page
- [ ] add like button and delete button
- [ ] add more places button, share and export the list button, 
- [ ] add a back button that links back to the trip page

**Comment by toshydev** [comment]
Minor typos in the value proposition:
As **a** User
I want *to* see a list of my places

The *like* and *delete* buttons are a big enough user story in itself. Maybe you could split the US.
Also the *Add more places*, *Share list*, *Export list* are quite the features for own user stories.

**Comment by malgosiam** [comment]
Thanks Anton! I will split it

**Comment by BenRodProd** [comment]
LGTM!
