### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by malgosiam** [malgosiam/capstone_chill-trip-planner#9]
## Value proposition

As an User
I want to be able to switch between the pages
So that I can navigate easier between different app pages

## Description

![Image](https://user-images.githubusercontent.com/17503662/231179713-67eadf02-17a1-4990-b64b-c38d72e0dcac.png)

## Acceptance criteria
- [ ] the navigation link with Chill Icon is displayed
- [ ] the navigation link with + Icon (add new trip) is displayed
- [ ] the navigation link with My Trips Icon is displayed
- [ ] clicking the Chill Icon redirect to the chill page
- [ ] clicking the + Icon redirect to the add new trip page
- [ ] clicking the My Trips Icon redirect to the list of the trips

## Tasks
- [ ] create the NavigationBar component
- [ ] create the component Layout that renders the Navigation component
- [ ] apply the Layout component in app.js
